[prompts]
    [extract_ontology]
    system_message = """You are an expert in creating ontologies"""
    human_message = """# Ontology from text:

    Extract an ontology. Do not draw it, but create a markdown table of relations with 3 columns in this order: source, target, relation name. And also create a list with 2 columns: the first contains the term name and the second column contains the term definition.
    the relations should only be mappeded to source, target, relations
    Use this text as a basis:

    {text}"""

    [graph_desc]
    system_message = """You are an expert in understanding relations and formatting it in text"""
    human_message = """This is the graph in gefx format:
    {graph}
    can you describe the graph in text?
    Can you please give the relations for it as well?
    Can you please write a summary of the interpretation?
    """

    [qna_bot]
    system_message = """You are an expert in answering questions from the given context"""
    human_message = """This is the content provided: {content} and the summary: {summary}
    Please answer the following question based on the content provided:
    {question}"""