[prompts]
    [extract_ontology]
    system_message = """You are an expert in creating ontologies"""
    human_message = """# Ontology from text:

    Extract an ontology. Do not draw it, but create a markdown table of relations with 3 columns in this order: source, target, relation name. And also create a list with 2 columns: the first contains the term name and the second column contains the term definition.
    Keep only one source and extract maximum relations for it
    Use this text as a basis:

    {text}"""
